### ISSUE TITLE
Stand up meeting 6/5/2021

### ISSUE THREAD

**Issue by mariordgez** [omar-labana/tic-tac-toe#3]
Very nice code implementation, methods are easy to read and understand.

**Comment by DanSam5K** [comment]
your work seems to be progressing pretty good and impressive!🔥👍

**Comment by YuvrajM108** [comment]
> your work seems to be progressing pretty good and impressive!🔥👍



> Very nice code implementation, methods are easy to read and understand.

Thank you guys so much.

**Comment by Aduda-Boaz** [comment]
The progress is good, keep up the good work and the clean code
